INSERT INTO "reservations" ("full_name", "email", "phone", "unique_id") VALUES ('John Smith', 'john.smith@smith.com', 5555555555, 1234);
INSERT INTO "reservations" ("full_name", "email", "phone", "unique_id") VALUES ('Bill Withers', 'bill.withers@music.com', 1234567891, 5432);
INSERT INTO "reservations" ("full_name", "email", "phone", "unique_id") VALUES ('Stevie Ray Vaughan', 'srv75@blues.com', 5555555555, 1234);
INSERT INTO "reservations" ("full_name", "email", "phone", "unique_id") VALUES ('Jimi Hendrix', 'JH69@woodstock.com', 9876543215, 6969);